Repository 1oT-organization/hotelity-frontend, pull requests merged in 2024-06, with the labels that each got.

#125 [Feat] 쿠폰/발급 쿠폰 전체 조회 기능
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/router/index.js
Labels: enhancement

#126 [Feat] 객실/객실 리스트 전체 조회
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/router/index.js
Labels: enhancement

#128 [Feat] 지점 리스트에 수정, 삭제 모달 및 팝업, 등록 추가
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/NoticeInfo.vue
  hotelity/src/router/index.js
Labels: enhancement

#129 [Feat] 호텔서비스/투숙-검색 및 필터 기능 구현 완료
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/Stay.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/hotel-service/stay/StaySearch.vue
  hotelity/src/router/index.js
Labels: enhancement

#131 [Feat] 객실 정보 페이지, 객실 리스트 구현 완료
  hotelity/src/component/hotel-management/RoomDetails.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/router/index.js
Labels: enhancement

#135 [Feat] 호텔 서비스/예약 - 캘린더 날짜 선택 시 체크인 일자 별 예약 리스트 출력
  hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/reservation/ReservationNavbar.vue
Labels: enhancement

#139 [Refactor] API 정의
  hotelity/src/api/apiClient.js
  hotelity/src/api/apiService.js
  hotelity/src/api/index.js
  hotelity/src/component/login/Login.vue
Labels: enhancement

#141 [Feat] 호텔 서비스/예약-캘린더 예약 건 수 이벤트 출력
  hotelity/index.html
  hotelity/src/api/apiService.js
  hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue
  hotelity/src/component/hotel-service/reservation/ReservationCheckinBtn.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/reservation/ReservationNavbar.vue
  hotelity/src/component/hotel-service/reservation/ReservationPage.vue
  hotelity/src/component/hotel-service/reservation/ReservationSearch.vue
  hotelity/src/router/index.js
  hotelity/src/router/router.js
Labels: enhancement

#142 [Refactor] Coupon / BranchList 수정
  hotelity/hotelity_logoico.ico
  hotelity/index.html
  hotelity/package.json
  hotelity/src/component/Test.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/marketing/CampaignSend.vue
  hotelity/src/component/marketing/TemplateInfo.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/marketing/TemplateSelect.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Voc.vue
  hotelity/src/component/sales/VocSelect.vue
  hotelity/src/router/index.js
  hotelity/src/router/router.js
Labels: enhancement

#143 [ Feat] 화면 라우팅 설정
  hotelity/src/api/apiClient.js
  hotelity/src/api/apiService.js
  hotelity/src/component/common/navbar/Navbar.vue
  hotelity/src/component/common/sidebar/Sidebar.vue
  hotelity/src/component/customer/Customer.vue
  hotelity/src/component/customer/CustomerInit.vue
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
  hotelity/src/router/router.js
Labels: enhancement

#144 [Refactor] RoomDetails 헤더 제거
  hotelity/src/App.vue
  hotelity/src/component/login/Login.vue
  hotelity/src/component/sales/CouponToCustomer.vue
  hotelity/src/component/sales/NoticeInfo.vue
  hotelity/src/router/router.js
Labels: enhancement

#145 [Feat] 고객 정보 조회 페이지 기본 틀 작성. (고객 json 중 일부 데이터 연결 완료)
  hotelity/src/component/customer/Customer.vue
Labels: enhancement

#147 [Refactor] 호텔 관리/객실- 객실 리스트 조회 시 객실등급명 th 태그 누락 수정
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/HotelService.vue
  hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/hotel-service/stay/StayPage.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/sales/NoticeInfo.vue
  hotelity/src/router/router.js
Labels: bug, refactor

#148 [Feature] 메인페이지
  hotelity/src/component/home/BarChart.vue
  hotelity/src/component/home/Home.vue
  hotelity/src/component/home/PieChart.vue
Labels: enhancement

#149 [Feat] Main 화면 구성
  hotelity/src/component/TestMainContent.vue
  hotelity/src/component/home/BarChart.vue
  hotelity/src/component/home/Home.vue
  hotelity/src/component/home/MainContent.vue
  hotelity/src/component/home/PieChart.vue
Labels: enhancement

#151 [refactor] 호텔 서비스/결제 - 결제 리스트에 결제 금액 컬럼 추가 및 데이터 누락 수정
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Voc.vue
  hotelity/src/router/router.js
Labels: refactor

#152 [Feature] login 시 동작 수정 및 추가
  hotelity/src/App.vue
  hotelity/src/api/apiService.js
  hotelity/src/assets/img/icon-user.png
  hotelity/src/component/common/navbar/Navbar.vue
  hotelity/src/component/login/Login.vue
  hotelity/src/router/router.js
  hotelity/src/store/index.js
Labels: enhancement

#153 Refactor: "추가된 GPT 관련 API 메소드 추출 및 API 파일에서 관리"
  hotelity/src/api/apiService.js
  hotelity/src/component/home/MainContent.vue
Labels: enhancement

#154 [Refactor] 메인 화면 AI 폰트 수정
  hotelity/src/api/apiClient.js
  hotelity/src/component/home/MainContent.vue
  hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue
  hotelity/src/component/hotel-service/stay/StayCheckoutBtn.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
Labels: refactor

#155 [Refactor] AI 대시보드 폰트 수정
  hotelity/src/component/home/MainContent.vue
Labels: refactor

#156 [refactor] 호텔 서비스/결제 - 결제 내역 조회 시 고객 코드 추가
  hotelity/src/api/apiClient.js
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
Labels: refactor

#157 [Refactor] 화면 코드 리팩토링
  hotelity/src/api/apiService.js
  hotelity/src/component/common/navbar/Navbar.vue
  hotelity/src/component/customer/Customer.vue
  hotelity/src/component/customer/CustomerInit.vue
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeInfo.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/css/style.css
  hotelity/src/router/router.js
Labels: duplicate

#159 [Refactor] localhost 주소 -> api로 변경
  hotelity/src/component/hotel-management/RoomDetails.vue
  hotelity/src/component/hotel-service/reservation/ReservationCheckinBtn.vue
  hotelity/src/component/hotel-service/stay/StayCheckoutBtn.vue
Labels: refactor

#161 [Feat] 호텔 서비스 / 코드 중간 통합
  hotelity/src/api/apiClient.js
  hotelity/src/component/hotel-service/reservation/ReservationInfo.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
Labels: enhancement

#162 [Feat] 페이징처리
  hotelity/src/App.vue
  hotelity/src/component/common/navbar/Navbar.vue
  hotelity/src/component/common/sidebar/Sidebar.vue
  hotelity/src/component/customer/CustomerInit.vue
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/home/BarChart.vue
  hotelity/src/component/home/PieChart.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/hotel-management/FacilityList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/login/Login.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/marketing/TemplateInfo.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
  hotelity/src/css/bootstrap.min.css
  hotelity/src/css/style.css
Labels: enhancement

#163 [Refactor] 전체 조회 수정
  hotelity/manifests/vue001dep.yml
  hotelity/package.json
  hotelity/src/api/apiService.js
  hotelity/src/component/customer/CustomerInit.vue
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/hotel-management/FacilityList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
Labels: refactor

#164 [Refactor] 전체 조회 스타일 추가
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/hotel-management/FacilityList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
Labels: refactor

#165 [Refactor] 리스트, 페이징 처리
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
  package-lock.json
Labels: enhancement

#166 [Refactor] 리스트 불필요 컬럼 제거 및 길이 조절
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
Labels: enhancement

#167 [Refactor/Feat] Footer, Loading 추가
  hotelity/src/App.vue
  hotelity/src/component/common/Footer.vue
  hotelity/src/component/customer/CustomerInit.vue
  hotelity/src/component/home/Home.vue
  hotelity/src/component/home/MainContent.vue
  node_modules/.package-lock.json
Labels: enhancement, refactor

#168 [Feat] 호텔서비스/예약-특정 예약 조회 모달창 추가 및 체크인 기능 수정
  hotelity/src/component/hotel-service/reservation/ReservationInfo.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
Labels: enhancement, refactor

#170 [Feat] 부대시설 상세 조회 페이지
  hotelity/src/App.vue
  hotelity/src/api/apiService.js
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/AncillaryDetails.vue
  hotelity/src/router/router.js
Labels: enhancement

#171 [Feat] 호텔서비스/투숙, 결제 리스트 및 정렬 스타일 변경
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
Labels: refactor

#173 [Feat] 호텔서비스/투숙-특정 투숙 내역 조회 및 체크아웃 방식 변경
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
Labels: enhancement, refactor

#175 [Bug] 호텔서비스/예약-캘린더 이벤트 누적 증가 에러 수정
  hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
Labels: bug

#177 [Feat] 공통 / 필터 컨테이너 넓이 및 위치 조정
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/FacilityList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/NoticeInfo.vue
  hotelity/src/component/sales/Voc.vue
Labels: refactor

#179 [Fix] 로그인 시 버그 수정
  hotelity/src/App.vue
  hotelity/src/component/login/Login.vue
Labels: enhancement

#180 [Refactor]
  hotelity/src/api/apiService.js
  hotelity/src/assets/js/combine.js
  hotelity/src/component/common/sidebar/Sidebar.vue
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/BranchList.vue
  hotelity/src/component/hotel-management/FacilityList.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/hotel-service/stay/StaySearch.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/Voc.vue
  hotelity/src/directives/clickOutside.js
Labels: refactor

#181 [Refactor] 엑셀 명 변경
  hotelity/src/api/apiService.js
  hotelity/src/component/common/navbar/Navbar.vue
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-management/Ancillary.vue
  hotelity/src/component/hotel-management/RoomList.vue
  hotelity/src/component/sales/Coupon.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Voc.vue
Labels: refactor

#182 [Refactor] 컬럼 길이 수정
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/Voc.vue
Labels: refactor

#184 [Refactor] 객실, 부대시설, 공지 - 수정 삭제
  hotelity/src/component/hotel-management/AncillaryDetails.vue
  hotelity/src/component/hotel-management/RoomDetails.vue
  hotelity/src/component/sales/NoticeInfo.vue
Labels: enhancement, refactor

#185 [Refactor] 반응형 템플릿 테스트
  hotelity/src/component/customer/CustomerList.vue
  hotelity/src/component/hotel-management/AncillaryDetails.vue
  hotelity/src/component/hotel-management/RoomDetails.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/sales/VocSelect.vue
Labels: refactor

#186 [Refactor] 사진 확대
  hotelity/src/component/hotel-management/AncillaryDetails.vue
Labels: enhancement, refactor

#187 [Feat] 호텔 서비스/투숙 수정 및 삭제 기능 구현 완료
  hotelity/src/api/apiService.js
  hotelity/src/component/hotel-service/stay/StayList.vue
Labels: enhancement

#188 [Refactor] 사진 확대 기능 수정
  hotelity/src/component/hotel-management/AncillaryDetails.vue
  hotelity/src/component/hotel-management/RoomDetails.vue
Labels: enhancement, refactor

#189 [Feat] 공통 / 사용자 가이드 pdf 다운로드 연동
  hotelity/src/api/apiService.js
  hotelity/src/component/common/Footer.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
Labels: enhancement

#190 [Refactor] 템플릿 리스트 조회 시 템플릿 내용 출력 글자 수 제한
  hotelity/src/component/common/Footer.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/VocSelect.vue
Labels: refactor

#191 [Feat] Voc 답변 기능 포함 VocSelect 구현 완료
  hotelity/src/api/apiService.js
  hotelity/src/component/sales/Voc.vue
  hotelity/src/component/sales/VocSelect.vue
Labels: enhancement

#194 [Refactor] 영업관리/공지 조회 페이지 스타일 수정
  hotelity/src/component/common/Footer.vue
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/sales/NoticeInfo.vue
  hotelity/src/component/sales/VocSelect.vue
Labels: refactor

#195 [Feat] 직원 정보 수정, 삭제 기능
  hotelity/src/component/employee/EmployeeInfo.vue
Labels: enhancement

#196 [Feat] 공지사항 등록 추가 완료
  hotelity/src/component/common/Footer.vue
  hotelity/src/component/common/navbar/Navbar.vue
  hotelity/src/component/hotel-management/AncillaryDetails.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/NoticeInit.vue
  hotelity/src/router/router.js
Labels: enhancement

#197 [Refactor] 영업 관리 / 공지 등록 시 페이지 새로고침
  hotelity/src/component/sales/Notice.vue
  hotelity/src/component/sales/NoticeInfo.vue
  hotelity/src/component/sales/NoticeInit.vue
Labels: refactor

#198 [Feat] 메인 로딩 수정
  hotelity/src/component/home/MainContent.vue
  hotelity/src/component/sales/NoticeInfo.vue
Labels: enhancement

#199 [Refactor] 직원 프로필 수정/삭제/이미지업로드 버튼 수정
  hotelity/src/component/employee/EmployeeInfo.vue
Labels: refactor

#200 [Refactor] 캠페인 발송화면/VOC리스트 수정
  hotelity/src/component/home/PieChart.vue
  hotelity/src/component/marketing/CampaignSend.vue
  hotelity/src/component/sales/Voc.vue
Labels: refactor

#201 [Bug] 마케팅/멤버십 등급, 발송 날짜 연동 오류 수정
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
  hotelity/src/component/marketing/Campaign.vue
Labels: bug

#202 [Refactor] 예약 컬럼 길이 수정
  hotelity/src/component/hotel-service/reservation/ReservationList.vue
Labels: refactor

#203 [Fix] 버그 수정
  hotelity/src/component/employee/EmployeeList.vue
  hotelity/src/component/hotel-service/payment/PaymentList.vue
  hotelity/src/component/hotel-service/stay/StayList.vue
  hotelity/src/component/marketing/Campaign.vue
  hotelity/src/component/marketing/TemplateInfo.vue
  hotelity/src/component/marketing/TemplateList.vue
  hotelity/src/component/sales/CouponIssue.vue
  hotelity/src/component/sales/Membership.vue
  hotelity/src/component/sales/VocSelect.vue
Labels: bug
